# image will be published to ghcr.io/<user>/<name>
name: atomic-tiles
# description will be included in the image's metadata
description: i3wm/sway image

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/sericea-nvidia
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
modules:
  - type: files
    files:
      - usr: /usr # copies config/files/usr into your images /usr
                  # put configuration files you want in /etc/ on a *booted*
                  # system in /usr/etc/ in the image.
      - etc: /etc # copies config/files/etc into your image's /etc immediately,
                  # for use with further modules.
  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      #  - https://copr.fedorainfracloud.org/coprs/gloriouseggroll/nobara-39/repo/fedora-39/gloriouseggroll-nobara-39-fedora-39.repo
    install:
        #- opentabletdriver % need new F40 repo...
        - android-file-transfer
        - fcitx5
        - fcitx5-autostart
        - fcitx5-gtk
        - fcitx5-lua
        - fcitx5-mozc # Japanese IME Module
        - fcitx5-qt
        - feh
        - terminus-fonts
        - fontawesome-fonts
        - gnome-settings-daemon # Perhaps there's a lighter xsettings daemon?
        - i3
        - i3blocks
        - i3lock
        - pamixer # Volume Control for i3
        - picom
        - qemu-system-arm
          #      - qt5ct # For QT Dark theme, can I get this working?
        - redshift-gtk
        - unclutter
        - virt-install
        - virt-manager
        - virt-viewer
        - xrandr
        - xclip
        - xdotool
        - maim
        - xset
        - zsh
        # Remote File Access
        - rclone # Can work as SMB client
        - fuse-sshfs
        - lftp
        # TUI
        - ncdu
        - iotop
        - btop
        - neovim # Remove in favor of appimage?
        # GUI
        - alacritty
        #
      # - micro
      # - starship
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
      # We use fcitx input rather than ibus
      - ibus
      - ibus-setup
      - ibus-libs
      - ibus-typing-booster
      - ibus-gtk3
      - ibus-gtk4
      - ibus-anthy-python
      - ibus-anthy
      - ibus-hangul
      - ibus-libzhuyin
      - ibus-libpinyin
      - ibus-m17n

  - type: default-flatpaks
    notify: true   # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
      # - org.gnome.Loupe
      # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08).
      # Only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Multiple install of same flatpaks with different branches is not supported.
      remove:
      # - org.gnome.eog
      #
    # A flatpak repo can also be added without having to install flatpaks,
    # as long as one of the repo- fields is present
    user:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
  - type: fonts
    fonts:
      nerd-fonts:
        - Hack
        - JetBrainsMono
        - SourceCodePro
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
