name: Build ISO

on:
  workflow_dispatch: # allow manually triggering builds

env:
  IMAGE_REPO: ghcr.io/${{ github.repository_owner }}

jobs:
  build-iso:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image_name:
          - atomic-tiles-main
          - atomic-tiles-nvidia
        major_version:
          - 41
        image_tag:
          - latest
    steps:
      - name: Build ISO
        uses: jasonn3/build-container-installer@main
        id: build
        with:
          arch: x86_64
          image_name: ${{ matrix.image_name }}
          image_repo: ${{ env.IMAGE_REPO }}
          image_tag: ${{ matrix.image_tag }}
          version: ${{ matrix.major_version }}
          variant: Server # Type of installer, Server should have user config
          iso_name: ${{ matrix.image_name }}-${{ matrix.image_tag }}-${{ matrix.major_version }}.iso
          enable_cache_dnf: "false"
          enable_cache_skopeo: "false"


      - name: Upload ISO as artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build.outputs.iso_name }}
          path: |
            ${{ steps.build.outputs.iso_path }}
            ${{ steps.build.outputs.iso_path }}-CHECKSUM
          if-no-files-found: error
          retention-days: 0
          compression-level: 0

